name: iris
description: "A modern IRC bouncer with websockets"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.2.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
#  emoji_picker_flutter: ^1.1.0
  image_picker: ^1.0.4      # <-- required for picking images
  http_parser: ^4.0.2       # <-- required for multipart uploads (already present)
  provider: ^6.0.5
  flutter_local_notifications: ^19.2.1 #^17.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  get_it: ^8.0.3
  package_info_plus: ^4.0.0
  flutter_secure_storage: ^9.0.0 # To securely store the user's identity key
  convert: ^3.1.1 # For hex encoding
  cryptography: ^2.7.0
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true