name: iris
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.0.0
  url_launcher: ^6.2.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
#  emoji_picker_flutter: ^1.1.0
  image_picker: ^1.0.4      # <-- required for picking images
  http_parser: ^4.0.2       # <-- required for multipart uploads (already present)
  provider: ^6.0.5
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "icon.png"